### ISSUE TITLE
[bug] Countries in map flash black on load

### ISSUE THREAD

**Issue by tipsy** [StephanWagner/svgMap#120]
# Steps to reproduce
* Open https://stephanwagner.me/create-world-map-charts-with-svgmap#svgMapDemoGDP
* Look at the map while the page loads

## Current workaround
```html
<div id="svgMap" class="unloaded"></div>
```
```css
.unloaded .svgMap-map-wrapper .svgMap-country {
    fill: var(--desired-starting-color);
}
```
```js
const map = new svgMap(...);
document.querySelector(".unloaded").classList.remove("unloaded");
```
