### ISSUE TITLE
Add ocean color variable

### ISSUE THREAD

**Issue by BenStigsen** [StephanWagner/svgMap#33]
Currently it's only possible to change `colorMax`, `colorMin` and `colorNoData` but not the ocean color (at least not when reading the README)

**Comment by StephanWagner** [comment]
Actually, the ocean color is just the background color of the wrapper. You could overwrite that with CSS:

```css
.svgMap-map-wrapper {
  background: #d9ecff;
}
```
